#
#  Import FILES LIBRARIES
import random
import string
from typing import Awaitable, Callable

from fastapi import FastAPI, Request

# from fastapi import FastAPI, Request, Response
from starlette.responses import Response

# from starlette.middleware.base import BaseHTTPMiddleware
# import time
# from collections import defaultdict
# from typing import Dict
#  Import FILES LIBRARIES
# #


app: FastAPI = FastAPI()

# Define the custom type for call_next for clarity: call_next takes a Request and returns an Awaitable Response
CallNext = Callable[[Request], Awaitable[Response]]


@app.middleware(middleware_type="http")
async def request_id_logging(request: Request, call_next: CallNext) -> Response:
    """A function call_next that will receive the request as a parameter.
    This function will pass the request to the corresponding path operation.
    Then it returns the response generated by the corresponding path operation.

    Args:
        request (Request): _description_
        call_next (_type_): _description_
    """
    response: Response = await call_next(request)
    random_letters = "".join(random.choice(seq=string.ascii_letters) for _ in range(10))
    print(f"Log {random_letters}")
    response.headers["X-Request-ID"] = random_letters
    return response


@app.get(path="/")
async def say_hi() -> str:
    return "Hello YouTube"


#
#  Import FILES LIBRARIES
#  Import FILES LIBRARIES
# #
# if __name__ == "__main__":
#     main()
